name: psyplot_gui_docs
channels:
    - psyplot/label/gh-migration
    - psyplot/label/dev
    - psyplot/label/master
    - psyplot
    - chilipp/label/conda-forge
dependencies:
    - python>3.5
    - qtconsole
    - ipykernel
    - pexpect
    - pygments
    - pyqt
    - sphinx
    - psy-simple
    - pip:
        - fasteners
        - autodocsumm
        - sphinx-argparse
